### ISSUE TITLE
domanda

### ISSUE THREAD

**Issue by faustf** [grevius5/godot-platform-tutorial#1]
ciao scusami non sapevo come contattarti vorrei chiederti una cosa  riguardo godot  , che e' piuttosto lunga e per farlo volevo scriverti una mail e' possibile scambiarsi  l email ?? grazie  la mia e' stfn77@gmail.com ciao

**Comment by grevius5** [comment]
Ciao @faustf scusa per il ritardo nella risposta.
Se vuoi parlare con me (e non solo) ed avere consigli su godot ti consiglio di unirti al canale discord tramite questo link: https://discord.gg/Rr2T7Z24qC
